=begin
#Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

#Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org.  <i>Please note that shipment events and subscription management are not covered yet by CMA CGM API.</i>  <br> This API is accessible through <ul> <li> <b> Public </b> connection (authentication with API Key): this allows to retrieve standard equipment moves (e.g. ready to be loaded, discharged), Transhipment moves (e.g. discharged and re-loaded onboard) and planned vessel departure and arrival dates. </li> <li> <b> Private </b> connection (authentication with Oauth2 client credentials): this allows to retrieve additional private events such as actual rail and ramp moves, planned departure and arrival dates for inland moves. These private events are available only if you (or your end customer) are identified on the booking as: Booking Party, Deciding Party, Consignee, Notifier or Shipper. </li> </ul> </br> For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

The version of the OpenAPI document: 2.2.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

# Common files
require 'cmacgm_client/api_client'
require 'cmacgm_client/api_error'
require 'cmacgm_client/version'
require 'cmacgm_client/configuration'

# Models
require 'cmacgm_client/models/address'
require 'cmacgm_client/models/base_equipment_event'
require 'cmacgm_client/models/base_event'
require 'cmacgm_client/models/base_event_body'
require 'cmacgm_client/models/base_shipment_event'
require 'cmacgm_client/models/base_transport_event'
require 'cmacgm_client/models/carrier_specific_data'
require 'cmacgm_client/models/customs_references'
require 'cmacgm_client/models/document_references_inner'
require 'cmacgm_client/models/document_type_code'
require 'cmacgm_client/models/empty_indicator_code'
require 'cmacgm_client/models/equipment_event'
require 'cmacgm_client/models/equipment_event_type_code'
require 'cmacgm_client/models/error'
require 'cmacgm_client/models/facility_code_list_provider'
require 'cmacgm_client/models/facility_type_code_trn'
require 'cmacgm_client/models/inline_response_default'
require 'cmacgm_client/models/location'
require 'cmacgm_client/models/mode_of_transport'
require 'cmacgm_client/models/operations_transport_event'
require 'cmacgm_client/models/reference'
require 'cmacgm_client/models/reference_type'
require 'cmacgm_client/models/references'
require 'cmacgm_client/models/seal'
require 'cmacgm_client/models/seal_source'
require 'cmacgm_client/models/seal_type'
require 'cmacgm_client/models/seals'
require 'cmacgm_client/models/search_move_on_commercial_cycle200_response_inner'
require 'cmacgm_client/models/shipment_event'
require 'cmacgm_client/models/shipment_event_type_code'
require 'cmacgm_client/models/sub_errors_inner'
require 'cmacgm_client/models/transport_call'
require 'cmacgm_client/models/transport_call_all_of_location'
require 'cmacgm_client/models/transport_event'
require 'cmacgm_client/models/transport_event_type_code'
require 'cmacgm_client/models/vessel'
require 'cmacgm_client/models/vessel_operator_carrier_code_list_provider'

# APIs
require 'cmacgm_client/api/events_api'

module CMACGMClient
  class << self
    # Customize default settings for the SDK using block.
    #   CMACGMClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
